os: centos
sudo: required

# This moves Kubernetes specific config files.
env:
  global:
    - MINISHIFT_VERSION_DIR="v1.30.0"
    - MINISHIFT_VERSION="1.30.0"
    - OC_VERSION="v3.11.0"
    - OC_COMMIT="0cbc58b"

    
before_script:
# Download minishift
- curl -Lo minishift.tgz https://github.com/minishift/minishift/releases/download/${MINISHIFT_VERSION_DIR}/minishift-${MINISHIFT_VERSION}-linux-amd64.tgz && tar -xzvpf minishift.tgz && chmod +x minishift-${MINISHIFT_VERSION}-linux-amd64/minishift && sudo mv minishift-${MINISHIFT_VERSION}-linux-amd64/minishift /usr/local/bin/
- curl -Lo oc.tgz https://github.com/openshift/origin/releases/download/${OC_VERSION}/openshift-origin-client-tools-${OC_VERSION}-${OC_COMMIT}-linux-64bit.tar.gz && tar -xzvpf oc.tgz && chmod +x openshift-origin-client-tools-${OC_VERSION}-${OC_COMMIT}-linux-64bit/oc && mv openshift-origin-client-tools-${OC_VERSION}-${OC_COMMIT}-linux-64bit/oc /usr/local/bin/ && chmod +x openshift-origin-client-tools-${OC_VERSION}-${OC_COMMIT}-linux-64bit/kubectl && mv openshift-origin-client-tools-${OC_VERSION}-${OC_COMMIT}-linux-64bit/kubectl /usr/local/bin/

script:
# Create example Redis deployment on Kubernetes.
- ./etc/scripts/install-on-minishift.sh

notifications:
  email: false
